### ISSUE TITLE
Better error message when pulling config dir fails

### ISSUE THREAD

**Issue by thomas-riccardi** [Deepomatic/dmake#249]
For each `dmake.yml` `.env.source` by default dmake tries to update with `git pull`, assuming it's a git repository. (It can be disabled with the `DMAKE_PULL_CONFIG_DIR` environment variable.)

When something goes wrong, the error is not great: most of the time it fails because the directory does not exist, mostly because the environment variable is not set.

Example:
```
Traceback (most recent call last):
  File "/usr/local/dmake/dmake/dmake", line 69, in <module>
    args.func(args)
  File "/usr/local/dmake/dmake/core.py", line 640, in make
    common.pull_config_dir(os.path.dirname(dmake_file.env.source))
  File "/usr/local/dmake/dmake/common.py", line 159, in pull_config_dir
    root_dir, _ = find_repo_root(root_dir)
  File "/usr/local/dmake/dmake/common.py", line 140, in find_repo_root
    root_dir = run_shell_command('git -C %s rev-parse --show-toplevel' % (path))
  File "/usr/local/dmake/dmake/common.py", line 96, in run_shell_command
    raise ShellError(subprocess_output_to_string(stderr))
dmake.common.ShellError: fatal: Not a git repository (or any of the parent directories): .git
```

Expected: something like:
> `foo/dmake.yml` `env` `source`: `${DEEPOMATIC_CONFIG_DIR}/dev.sh` is not a valid path/git repository: <the low-level error>

# TODO
- [ ] enrich the low-level exception with user-actionable doc
- [ ] maybe enable strict mode for bash expansion for `.env.source` ? we never changed the strictness on existing fields to avoid breakages, but maybe in this specific case it's a good idea.
- [ ] maybe don't git pull if it's not in a git repository; but still raise an early error if the file doesn't exist?
